## bugfix/box

* Fixed the error message in an attempt to insert into a tuple the size of
  which equals to `box.schema.FIELD_MAX` (gh-6198).
